### ISSUE TITLE
Config error with AiA Terrain?

### ISSUE THREAD

**Issue by Wargog** [denisio/Arma3-Epoch-Linux-Server#5]
Hi, there is an error with the AiA Chernarus mission file in the pack, I've set everything up properly on the client and server, but I don't know what's wrong with it, it won't let me join with this error. I took a screenshot here http://puu.sh/gR0Ie/6876a34dbb.png

**Comment by g0shed** [comment]
Make sure you update epoch as well, not just hive

**Comment by Wargog** [comment]
It is a fresh install, Epoch 0.3.0.1 is installed along with the latest files from this repo, that's it

**Comment by Wargog** [comment]
Anyone? I've installed AiA on the server side but it is still giving me the errors.

**Comment by Fumler** [comment]
@Wargog I am currently running Chernarus on my server. You probably need to edit epoch.sh and add in the @allinarmaterrainpack or @allinarmaterrainpack, depending on which one you are using. (I suggest lite version for performance). You also need keys for both the lite version and the normal version of AiATP in your keys folder.

**Comment by Wargog** [comment]
I did do that, it just doesn't work, I've given up on this and just moved to Windows anyway.
