### ISSUE TITLE
group issue

### ISSUE THREAD

**Issue by Elenedeath** [denisio/Arma3-Epoch-Linux-Server#7]
when player, create or join a group cant build.
the group leader spawn a frequency and after all the team can build but not now only the leader can build and all the team see like if it doesnt have group.

error i see on console
when i set keviin to group leader
[callExtension](200|Group:uid-keviin): 110|Group:uid_hikage|["hikage","Hikage",4,[["uid-keviin","Keviin Skyline"]],[]]
Error handler111(SET): ERR syntax error

and just after when im killed
1:04:11 "GROUP: No Group Selected ["","uid-keviin",false,false,B Alpha 1-1:2 (Keviin Skyline) REMOTE,""u4iu4ku5su7qu5mu8tu5nu9t""]"

kevvin spawn a jammer i join his group i see on console

when receive the request
 1:23:06 "DEBUG GROUP ["uid_hikage","uid-keviin","Skyline",B Alpha 1-3:1 (Keviin Skyline) REMOTE,""n8bn81n2gn5ln8rn1gn7yn8cn9en7g""] - B Alpha 2-1:1 (Hikage) REMOTE"

when i accept the request
  1:23:34 "GROUP: Update ["uid-keviin","uid_hikage",true,false,B Alpha 2-1:1 (Hikage) REMOTE,""p3pp9cp13p64p5vp3op1rp7k""]"

but i doesnt see the group ingame and cant build

**Comment by denisio** [comment]
fixed in epochserver.so

**Comment by Elenedeath** [comment]
yeah i try with my friend and work fine now.
thanks you for your great work and very quick fix
